
TEXT_THRESHOLD=0.7

# QuickDraw 데이터 설정
IMAGE_SIZE = (32, 32)  # 이미지 크기 (너비, 높이)
ENG_CATEGORIES= [
    "aircraft carrier",
    "airplane",
    "alarm clock",
    "ambulance",
    "angel",
    "apple",
    "arm",
    "axe",
    "backpack",
    "banana",
    "bandage",
    "baseball",
    "basketball",
    "bat",
    "bathtub",
    "bed",
    "bee",
    "bicycle",
    "bird",
    "birthday cake",
    "book",
    "bowtie",
    "bread",
    "broom",
    "bucket",
    "bus",
    "bush",
    "butterfly",
    "cake",
    "calendar",
    "camera",
    "campfire",
    "candle",
    "car",
    "carrot",
    "cat",
    "cell phone",
    "chair",
    "church",
    "circle",
    "cloud",
    "compass",
    "computer",
    "cookie",
    "couch",
    "cow",
    "crab",
    "crocodile",
    "crown",
    "cup",
    "dog",
    "dolphin",
    "donut",
    "door",
    "duck",
    "ear",
    "elephant",
    "envelope",
    "eye",
    "eyeglasses",
    "face",
    "fan",
    "fire hydrant",
    "fish",
    "flower",
    "fork",
    "frog",
    "frying pan",
    "garden",
    "giraffe",
    "grapes",
    "guitar",
    "hammer",
    "hat",
    "helicopter",
    "hexagon",
    "hockey stick",
    "horse",
    "ice cream",
    "jacket",
    "kangaroo",
    "keyboard",
    "knife",
    "ladder",
    "laptop",
    "leaf",
    "leg",
    "lighthouse",
    "lightning",
    "lion",
    "lobster",
    "lollipop",
    "mailbox",
    "map",
    "marker",
    "megaphone",
    "moon",
    "motorbike",
    "mountain",
    "mug"
]

KOR_CATEGORIES= ["항공모함", "비행기", "알람시계", "앰뷸런스", "천사", "시과", "팔", "도끼", "백팩", "바나나", "붕대", "야구", "농구", "야구배트", "욕조", "침대", "꿀벌", "자전거", "새", "생일케이크", "책", "나비넥타이",
            "빵", "빗자루", "양동이", "버스", "수풀", "나비", "케이크", "달력", "카메라", "모닥불", "양초", "차", "당근", "고양이", "핸드폰", "의자", "교회", "동그라미", "구름", "컴파스", "컴퓨터", "쿠키",  "소파", "소", "게", "악어",
            "왕관", "컵", "개", "돌고래", "도넛", "문", "오리", "귀", "코끼리", "편지봉투", "눈", "안경", "얼굴", "선풍기", "소화기", "물고기", "꽃", "포크", "개구리", "프라이팬", "정원", "기린", "포도", "기타", "망치", "모자", "헬리콥터", "육각형", "하키 채", "말", "재킷",
            "캥거루", "키보드", "칼", "사다리", "노트북", "나뭇잎", "다리", "등대", "번개", "사자", "가재", "막대사탕", "우체통", "지도", "보드마카", "확성기", "달", "오토바이", "산", "머그컵"]


MODEL_PATH= 'src/image/trained_model/'